<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Classroom-201" failures="1" tests="2" name="NewCycleAgain" time="21.773" errors="0" timestamp="2025-07-03T10:55:01 IST">
  <testcase classname="runnerscripts.TestcCase01" name="AddEmp" time="0.001">
    <skipped/>
  </testcase> <!-- AddEmp -->
  <testcase classname="runnerscripts.TestcCase2" name="FetchTitle" time="0.012">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at runnerscripts.TestcCase2.FetchTitle(TestcCase2.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- FetchTitle -->
</testsuite> <!-- NewCycleAgain -->
